repos:
-   repo: local
    hooks:
      - id: lint
        name: lint
        entry: docker-compose up --exit-code-from lint lint
        language: system
        types: [python]
        pass_filenames: false
-   repo: local
    hooks:
      - id: tests
        name: tests
        entry: docker-compose up --exit-code-from tests tests
        language: system
        types: [python]
        pass_filenames: false
-   repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
