version: "3.7"

x-build: &default-build
  context: .
  dockerfile: Dockerfile

services:
  lola-app:
    build: *default-build
    command: python Lola/main.py
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - 80:80
    networks:
      - back

  lint:
    container_name: lola-lint
    build: *default-build
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - back
    command: ["./scripts/start-lint.sh"]

  tests:
    container_name: lola-tests
    build: *default-build
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    command: ["pytest", "tests"]

networks: 
  back:
    external:
      name: back-bocuse